### ISSUE TITLE
Not really an issue but Idk where else to write this

### ISSUE THREAD

**Issue by ichdropedich** [PsiLupan/MakeLobbiesGreatAgain#117]
hello, I used MLGA since its release and I love it. 
I wanted to ask you if you could make the newest version with the old taskbar icon tray? It was Jake and I loved it. Bald Dwight would be awesome aswell. Thanks for this beautiful and useful program, take care!

**Comment by PsiLupan** [comment]
You're welcome to change it back via the icon.png file - The original should be available under b0d7c1bc9a22eb1837a2a790ebc9e8ff5f9c1095 . You can even open the JAR file with a ZIP program, like WinRAR or 7-Zip, and make that change.

I'm not really interested in adding it back myself, because I'd like to keep myself distanced from BHVR's IPs.

That file also had a EXIF tag for geolocation that was to Area 51, which I guess I was 2 years early to the raid jokes.
