### ISSUE TITLE
High cpu usage

### ISSUE THREAD

**Issue by gawdsed** [PsiLupan/MakeLobbiesGreatAgain#13]
see image, I believe I was in game at this point. Might me missing a sleep in a loop somewhere?

http://imgur.com/a/MMzWX

**Comment by gawdsed** [comment]
nope, happens after the game is done as well. Re-starting the app makes it use very little cpu usage... 0.7 ish. Haven't look at the source yet, but getting the country/host/ping... is that all added to an array? Could be that it's not cleared and has to re-resolve every new entry

**Comment by gawdsed** [comment]
joined a second game and still nothing. I did have the app running for at least 5 games before it happened... I also played SWF. I'll keep and eye out to see what's bugging it.

**Comment by gawdsed** [comment]
Found it. double right clicking the GUI and moving it causes a constant CPU spike.

**Comment by PsiLupan** [comment]
Double-clicking removes the sleep while the UI is unlocked, so that it follows the mouse correctly and doesn't lag behind. Double-clicking to relock will reactive the sleep.

Right-clicking twice would just turn the countryName var to true, then false again.

Are you say CPU usage says high after relocking the window?

**Comment by PsiLupan** [comment]
I tested and tried to reproduce. The only time CPU stays high is if the window remains unlocked for dragging.

**Comment by PsiLupan** [comment]
https://github.com/PsiLupan/MakeLobbiesGreatAgain/commit/5904cc39770850d6f2d330048bfb72ae9af89f85

Resolved.
