### ISSUE TITLE
Country lookup

### ISSUE THREAD

**Issue by Kilowog01** [PsiLupan/MakeLobbiesGreatAgain#16]
Add the Country lookup back please. Leave it optional for those who don't like it. I liked it a lot.

**Comment by PsiLupan** [comment]
The reasons I removed it was because I got messages that users were banned from the API site for leaving the program open as killer. Plus, it would only be supported for survivor.

I may add it back at some point, but I'd prefer to do it after having a concrete method to determine if the person is playing killer or survivor. On top of implementing a timer for killers that would lower how fast they roll through usage.

**Comment by exieln** [comment]
Will this ever return? i heard the program was unblocked by EAC.

**Comment by PsiLupan** [comment]
Country code lookup is still on the backburner. I haven't decided if/when I'll implement it currently, as I may just return the VPN check.
