### ISSUE TITLE
No killer/0 ms ping killer

### ISSUE THREAD

**Issue by SalSolo** [PsiLupan/MakeLobbiesGreatAgain#42]
Some killers that game matches me with, seem to have found a way to block this addon or it is a bug of some sort. Every few games there is a case that this addon says "No killer" or  "Killer: 0" ms ping. Anyone else having this issue?

Oh, and usually they are the same killers, got matched with a guy 3 times in a row, and 3 times i could not see his ping.

**Comment by PsiLupan** [comment]
I've seen a survivor with similar. I believe they don't have routers, meaning they have a WAN IP because their computer connects directly to the modem. There isn't a STUN packet being sent.

I'm not sure of a simple fix for this, if one exists. I can recreate this situation for myself, but I will need some time to figure it out.
