### ISSUE TITLE
MLGA backup error

### ISSUE THREAD

**Issue by MLGALover** [PsiLupan/MakeLobbiesGreatAgain#66]
## Hello.

So, i use this Tool for 2 Months now. @PsiLupan 

I also enabled the backup function which was added with one of the latest Releases. I never had any errors/issues with the backup creating in any Way.
2 Days ago i was getting the Message " WARNING: possible loss of progress. Backup was not created." **(See Attachment)**

Like i said i installed MLGA in the Way it should be, so no installation issues or anything like that. Backup is created in my %appdata% like it should be. No Idea why this Error suddently came up out of nowhere.

I would love to get this fixed since i do really enjoy the Backup function of MLGA! :)

- Frank_
![mlgaerror](https://user-images.githubusercontent.com/29469683/27205296-4acc5406-5230-11e7-8a8f-46ce4360935b.png)

**Comment by PsiLupan** [comment]
That error occurs if there's a 9KB difference between your backed up save file, and the one that it's trying to replace it with. A file size difference like that could mean that your saved game progress is being wiped due to a bug.

If that's not the case and your save file is working fine, you can remove the backups from the %APPDATA%/MLGA/ folder and it won't detect the files to do the comparison against.

**Comment by MLGALover** [comment]
Thanks for the quick Response. I will try to fix it tommorow when I'm back home!

**Comment by MLGALover** [comment]
So, i just deleted the old Save Game backup and it creates completely new ones now. Seems to work. 

Thank you PsiLupan.

i m mark that as resolved.

**Comment by MLGALover** [comment]
Sorry, have to re-open quickly.

So, after 1 hour it stopped working again.

I will post my MLGA backup folder, the files seem to be big enough.

![mlgafolder01](https://user-images.githubusercontent.com/29469683/27233075-93fa6748-52b8-11e7-80a3-c92e4f270ad0.png)

![mlgafolder02](https://user-images.githubusercontent.com/29469683/27233084-98b97e2c-52b8-11e7-8322-310efec9fed9.png)

I just don't know, i REALLY want this backup feature to be working :( i never touched my save game in any Way, i only played the Game and then suddently one Day this error is coming.

I dont know what i should do to fix this...

**Comment by MLGALover** [comment]
Here is my Original SaveGame Folder:

![originalsavegamefolder01](https://user-images.githubusercontent.com/29469683/27233296-42300232-52b9-11e7-9495-06af1801b4bc.png)


![originalsavegamefolder02](https://user-images.githubusercontent.com/29469683/27233299-46611e86-52b9-11e7-9e2e-45dc2620d45c.png)

**Comment by PsiLupan** [comment]
Go to the Steam/userdata/steamID#/381210/remote/ProfileSaves folder and
screenshot that.

Your backups are massive. Like, 100x the size of mine for some reason.

**Comment by MLGALover** [comment]
@PsiLupan just uploaded the Screenshots above.

**Comment by PsiLupan** [comment]
Yeah, saw and deleted my comment as I sent.

Like I said, your backups are literally 100x the size of mine. Mine clock in at 29KB. I guess as far as account data goes, are you maxed out with every character or something? It seems strange your file is that big.

I'll add a fix to the next version this afternoon to hopefully deal with that.

**Comment by MLGALover** [comment]
@PsiLupan 

Yes i'm maxed out, i play this Game since Months and almost every Day with friends. Only thing i do right now that can make my SaveFile grow i guess, is the unlocking Items from my Bloodweb.

i think that have to be the problem then.

Thank you for trying to get a fix ready. If it doesn't work it's also fine. It's my fault to have such a big Save file :D

**Comment by PsiLupan** [comment]
Should be fixed with 3524245d681065d6205aa2f16659db9c4f367ca7 as I'll be checking to make sure the file isn't less than 12KB in total size, which would be close to the size of a new file. That way, you don't get pestered every time.

This won't prevent backing up small losses of progress like a bloodweb resetting, but that should be fine with multiple backups.

I'll go ahead and close out this issue, and the official release should be in about ~7 hours, once I'm home from work.
